name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}

      - name: Bump file and commit
        run: |
          date > test.txt

          git config --global user.email "github-actions@ianunruh.com"
          git config --global user.name "GitHub Actions"

          git commit -av -m "Bump test version"
          git push
