name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump file and commit
        run: |
          date > test.txt

          git config --global user.email "github-actions@ianunruh.com"
          git config --global user.name "GitHub Actions"

          git remote set-url origin https://ianunruh:${{ secrets.GH_BOT_TOKEN }}@github.com/ianunruh/gha-test.git

          git commit -av -m "Bump test version"
          git push
